// <auto-generated />
using Assgn2.AssetTracking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assgn2.AssetTracking.Data.Migrations
{
    [DbContext(typeof(AssetContext))]
    partial class AssetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assgn2.AssetTracking.Domain.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.ToTable("Asset");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetTypeId = 1,
                            Description = "2 in 1 Laptop",
                            Manufacturer = "Dell",
                            Model = "D3D 3D3",
                            SerialNumber = "xx0303Dellxx",
                            TagNumber = "x0Asst"
                        },
                        new
                        {
                            Id = 2,
                            AssetTypeId = 2,
                            Description = "Gaming monitor",
                            Manufacturer = "Acer",
                            Model = "AAA 111",
                            SerialNumber = "tt2020Acertt",
                            TagNumber = "x25Asst"
                        },
                        new
                        {
                            Id = 3,
                            AssetTypeId = 3,
                            Description = "6.4 inch Smart Phone",
                            Manufacturer = "Polycom",
                            Model = "P30 P30",
                            SerialNumber = "ss1342Polycomss",
                            TagNumber = "x42Asst"
                        },
                        new
                        {
                            Id = 4,
                            AssetTypeId = 1,
                            Description = "HP Chromebook 13",
                            Manufacturer = "HP",
                            Model = "HP1 101",
                            SerialNumber = "mn2000HPmn",
                            TagNumber = "x76Asst"
                        },
                        new
                        {
                            Id = 5,
                            AssetTypeId = 3,
                            Description = "Touch Screen All-In-One",
                            Manufacturer = "Cisco",
                            Model = "876 CIS",
                            SerialNumber = "aa1987Ciscoaa",
                            TagNumber = "x14Asst"
                        });
                });

            modelBuilder.Entity("Assgn2.AssetTracking.Domain.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AssetType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Monitor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Phone"
                        });
                });

            modelBuilder.Entity("Assgn2.AssetTracking.Domain.Asset", b =>
                {
                    b.HasOne("Assgn2.AssetTracking.Domain.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
